# modules/excel_export.py
from __future__ import annotations
import io
from collections import Counter
import streamlit as st

def generate_excel(gene, pdata, cv, scored, gi, gnomad, string_data, drugs_data, trials_data, ot_data, diseases, papers, patient_data, roi_data, am_scores, hotspots) -> bytes:
    """Generate a comprehensive multi-sheet Excel workbook with all protein data."""
    try:
        import openpyxl
        from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except ImportError:
        return b""

    wb = openpyxl.Workbook()

    # Colour palette
    DARK = "0D1117"
    BLUE = "0066AA"
    CYAN = "00E5FF"
    RED = "FF2D55"
    ORANGE = "FF8C42"
    YELLOW = "FFD60A"
    GREEN = "00C896"
    PURPLE = "A855F7"
    WHITE = "FFFFFF"
    LGREY = "F0F4F8"

    def hdr(ws, row, col, text, bg=BLUE, fg=WHITE, bold=True, sz=11):
        cell = ws.cell(row=row, column=col, value=text)
        cell.fill = PatternFill("solid", fgColor=bg)
        cell.font = Font(bold=bold, color=fg, size=sz, name="Calibri")
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        return cell

    def val(ws, row, col, text, bg=None, fg="111111", bold=False, sz=10, wrap=True):
        cell = ws.cell(row=row, column=col, value=text)
        if bg:
            cell.fill = PatternFill("solid", fgColor=bg)
        cell.font = Font(bold=bold, color=fg, size=sz, name="Calibri")
        cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=wrap)
        return cell

    def section_hdr(ws, row, col, text, width=8):
        cell = ws.cell(row=row, column=col, value=text)
        cell.fill = PatternFill("solid", fgColor=DARK)
        cell.font = Font(bold=True, color=CYAN, size=12, name="Calibri")
        cell.alignment = Alignment(horizontal="left", vertical="center")
        if width > 1:
            ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col + width - 1)
        return cell

    def rank_colour(rank):
        return {"CRITICAL": RED, "HIGH": ORANGE, "MEDIUM": YELLOW, "NEUTRAL": "888888"}.get(rank, LGREY)

    # Sheet 1: Executive Summary
    ws1 = wb.active
    ws1.title = "📋 Summary"
    ws1.sheet_view.showGridLines = False
    ws1.column_dimensions["A"].width = 28
    ws1.column_dimensions["B"].width = 45

    section_hdr(ws1, 1, 1, f"🧬 PROTELLECT — {gene} Intelligence Report", 2)
    ws1.row_dimensions[1].height = 30
    val(ws1, 2, 1, f"Generated by Protellect | Data: UniProt, ClinVar, gnomAD, STRING, OpenTargets, PubMed", bg=LGREY, sz=9)
    ws1.merge_cells("A2:B2")

    row = 4
    from modules.data_processing import g_name
    fields = [
        ("Gene Symbol", gene),
        ("Protein Name", g_name(pdata)[:80]),
        ("UniProt ID", pdata.get("primaryAccession", "")),
        ("Organism", pdata.get("organism", {}).get("scientificName", "")),
        ("Protein Length", f"{pdata.get('sequence', {}).get('length', '')} amino acids"),
        ("Genomic Integrity", gi.get("verdict", "")),
        ("Invest Verdict", gi.get("pursue", "").upper()),
        ("Pathogenic Variants", gi.get("n_pathogenic", 0)),
        ("Total ClinVar Variants", gi.get("n_total", 0)),
        ("Variant Density", f"{gi.get('density', 0) * 100:.2f}%"),
        ("pLI (LoF intolerance)", gnomad.get("pLI", "N/A") if gnomad else "N/A"),
        ("o/e LoF", gnomad.get("oe_lof", "N/A") if gnomad else "N/A"),
        ("Known drugs (DGIdb/OT)", len(drugs_data)),
        ("Active clinical trials", len(trials_data)),
        ("Estimated global patients", f"{patient_data.get('estimated_global_patients', 0):,}" if patient_data else "N/A"),
        ("Orphan Drug eligible", "YES" if patient_data.get("orphan_eligible") else "NO"),
    ]
    hdr(ws1, row, 1, "Field", DARK, CYAN)
    hdr(ws1, row, 2, "Value", DARK, CYAN)
    row += 1
    for k, v0 in fields:
        bg2 = {"prioritise": "C8F0E0", "proceed": "FFE8CC", "selective": "FFFACC", "caution": "FFF0CC", "deprioritise": "F0E0E8", "neutral": LGREY}.get(gi.get("pursue", ""), None) if "Verdict" in k else None
        val(ws1, row, 1, k, LGREY, bold=True)
        val(ws1, row, 2, str(v0), bg2)
        row += 1

    # Sheet 2: ClinVar Variants
    ws2 = wb.create_sheet("🔬 ClinVar Variants")
    ws2.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("ML Rank", 12), ("Variant", 40), ("Protein Change", 18), ("Position", 10), ("ClinVar Sig.", 22), ("Disease / Condition", 40), ("ML Score", 10), ("Germline", 10), ("Somatic", 10), ("Review Status", 22), ("ClinVar URL", 40)], 1):
        ws2.column_dimensions[get_column_letter(col)].width = w
        hdr(ws2, 1, col, name, DARK, CYAN)

    for r_idx, v2 in enumerate(scored, 2):
        rk = v2.get("ml_rank", "NEUTRAL")
        rk_clr = rank_colour(rk)
        cells_data = [
            (rk, rk_clr, WHITE, True),
            (v2.get("variant_name", "")[:60], None, "111111", False),
            (v2.get("variant_name", "")[:30], None, "111111", False),
            (v2.get("start", ""), None, "111111", False),
            (v2.get("sig", ""), None, "333333", False),
            (v2.get("condition", "")[:80], None, "333333", False),
            (v2.get("ml", 0), None, "111111", False),
            ("Yes" if v2.get("germline") else "No", "C8F0E0" if v2.get("germline") else None, "111111", False),
            ("Yes" if v2.get("somatic") else "No", "F0E0E8" if v2.get("somatic") else None, "111111", False),
            (v2.get("review", "")[:30], None, "555555", False),
            (v2.get("url", ""), None, "0066AA", False),
        ]
        for c_idx, (txt, bg, fg, bold) in enumerate(cells_data, 1):
            cell = val(ws2, r_idx, c_idx, txt, bg, fg, bold, 9)
            if c_idx == 11 and txt:
                cell.hyperlink = txt
                cell.style = "Hyperlink"

    # Sheet 3: Disease Associations
    ws3 = wb.create_sheet("🏥 Diseases")
    ws3.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("Disease Name", 40), ("Inheritance", 20), ("Mutation Type", 25), ("ClinVar Variants", 15), ("Severity Est.", 12), ("Description", 60)], 1):
        ws3.column_dimensions[get_column_letter(col)].width = w
        hdr(ws3, 1, col, name, DARK, CYAN)

    cond_counts_e = {}
    for v2 in cv.get("variants", []):
        if v2.get("score", 0) >= 2:
            for c2 in v2.get("condition", "").split(";"):
                c2 = c2.strip()
                if c2:
                    cond_counts_e[c2] = cond_counts_e.get(c2, 0) + 1

    for r_idx, d2 in enumerate(diseases, 2):
        nm2 = d2.get("name", "")
        cv_cnt = max((v for k, v in cond_counts_e.items() if nm2.lower()[:15] in k.lower()), default=0)
        sev2 = min(95, 20 + cv_cnt * 8 + (20 if "dominant" in d2.get("inheritance", "").lower() else 0))
        sev_bg = "FFD0D0" if sev2 > 70 else "FFE8CC" if sev2 > 40 else "FFFACC"
        val(ws3, r_idx, 1, nm2, None, "111111", True, 10)
        val(ws3, r_idx, 2, d2.get("inheritance", "Unknown"))
        val(ws3, r_idx, 3, d2.get("mutation_type", "Variant"))
        val(ws3, r_idx, 4, cv_cnt)
        val(ws3, r_idx, 5, f"{sev2}/100", sev_bg, "333333", True)
        val(ws3, r_idx, 6, d2.get("desc", "")[:200])

    # Sheet 4: Experiment ROI Roadmap
    ws4 = wb.create_sheet("🧪 Experiment Roadmap")
    ws4.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("Priority Rank", 10), ("Experiment", 40), ("Category", 18), ("ROI Score", 12), ("ROI Label", 14), ("Est. Cost", 14), ("Timeline", 12), ("P(Success)", 12), ("Rationale", 70)], 1):
        ws4.column_dimensions[get_column_letter(col)].width = w
        hdr(ws4, 1, col, name, DARK, CYAN)

    for r_idx, exp_e in enumerate(roi_data, 2):
        pri_bg = {"🟢 Excellent": "C8F0E0", "🟡 Good": "FFFACC", "🟠 Fair": "FFE8CC", "🔴 Low": "FFD0D0"}.get(exp_e.get("roi_label", ""), "F5F5F5")
        val(ws4, r_idx, 1, r_idx - 1, None, "111111", True)
        val(ws4, r_idx, 2, exp_e.get("name", ""), None, "111111", True, 10)
        val(ws4, r_idx, 3, exp_e.get("category", ""))
        val(ws4, r_idx, 4, exp_e.get("roi", 0), pri_bg, "111111", True)
        val(ws4, r_idx, 5, exp_e.get("roi_label", ""), pri_bg)
        val(ws4, r_idx, 6, f"${exp_e.get('cost_usd', 0):,}" if exp_e.get('cost_usd', 0) > 0 else "FREE")
        val(ws4, r_idx, 7, f"{exp_e.get('time_weeks', 0)} weeks")
        val(ws4, r_idx, 8, f"{exp_e.get('p_success', 0) * 100:.0f}%")
        val(ws4, r_idx, 9, exp_e.get("rationale", "")[:300], sz=9)

    # Sheet 5: Drug Landscape
    ws5 = wb.create_sheet("💊 Drug Landscape")
    ws5.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("Drug / Compound", 30), ("Interaction Type", 20), ("Sources", 30), ("Database", 12), ("Link", 40)], 1):
        ws5.column_dimensions[get_column_letter(col)].width = w
        hdr(ws5, 1, col, name, DARK, CYAN)

    row5 = 2
    for d_e in drugs_data:
        val(ws5, row5, 1, d_e.get("drug", ""), None, "111111", True)
        val(ws5, row5, 2, d_e.get("type", ""))
        val(ws5, row5, 3, d_e.get("sources", "")[:50])
        val(ws5, row5, 4, "DGIdb")
        url_e = d_e.get("url", "")
        cell_e = val(ws5, row5, 5, url_e, None, "0066AA")
        if url_e:
            cell_e.hyperlink = url_e
            cell_e.style = "Hyperlink"
        row5 += 1

    # Sheet 6: Protein Interactions
    ws6 = wb.create_sheet("🔗 Interactions")
    ws6.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("Partner Protein", 22), ("Combined Score", 16), ("Experimental Score", 18), ("Co-expression", 16), ("STRING URL", 40)], 1):
        ws6.column_dimensions[get_column_letter(col)].width = w
        hdr(ws6, 1, col, name, DARK, CYAN)

    for r_idx, si in enumerate(string_data, 2):
        bg_si = "C8F0E0" if si.get("score", 0) > 800 else "FFFACC" if si.get("score", 0) > 600 else None
        val(ws6, r_idx, 1, si.get("partner", ""), None, "111111", True)
        val(ws6, r_idx, 2, si.get("score", 0), bg_si, "111111", True)
        val(ws6, r_idx, 3, si.get("experiments", 0))
        val(ws6, r_idx, 4, si.get("coexpression", 0))
        url_si = si.get("url", "")
        cell_si = val(ws6, r_idx, 5, url_si, None, "0066AA")
        if url_si:
            cell_si.hyperlink = url_si
            cell_si.style = "Hyperlink"

    # Sheet 7: Clinical Trials
    ws7 = wb.create_sheet("🏥 Clinical Trials")
    ws7.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("NCT ID", 15), ("Title", 80), ("Status", 22), ("Phase", 10), ("ClinicalTrials.gov URL", 50)], 1):
        ws7.column_dimensions[get_column_letter(col)].width = w
        hdr(ws7, 1, col, name, DARK, CYAN)

    for r_idx, t_e in enumerate(trials_data, 2):
        status_bg = "C8F0E0" if "RECRUIT" in t_e.get("status", "") else "FFE8CC"
        val(ws7, r_idx, 1, t_e.get("nct_id", ""), None, "0066AA", True)
        val(ws7, r_idx, 2, t_e.get("title", "")[:150])
        val(ws7, r_idx, 3, t_e.get("status", ""), status_bg)
        val(ws7, r_idx, 4, t_e.get("phase", "?"))
        url_t = t_e.get("url", "")
        cell_t = val(ws7, r_idx, 5, url_t, None, "0066AA")
        if url_t:
            cell_t.hyperlink = url_t
            cell_t.style = "Hyperlink"

    # Sheet 8: Variant Hotspots
    ws8 = wb.create_sheet("🎯 Hotspots")
    ws8.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("Hotspot #", 10), ("Start Residue", 14), ("End Residue", 14), ("Pathogenic Count", 16), ("Fold Enrichment", 16), ("Positions", 60)], 1):
        ws8.column_dimensions[get_column_letter(col)].width = w
        hdr(ws8, 1, col, name, DARK, CYAN)

    for r_idx, hs in enumerate(hotspots, 2):
        fe = hs.get("fold_enrichment", 0)
        hs_bg = "FFD0D0" if fe > 8 else "FFE8CC" if fe > 4 else "FFFACC"
        val(ws8, r_idx, 1, r_idx - 1, hs_bg, "111111", True)
        val(ws8, r_idx, 2, hs.get("start", 0))
        val(ws8, r_idx, 3, hs.get("end", 0))
        val(ws8, r_idx, 4, hs.get("count", 0), hs_bg, "111111", True)
        val(ws8, r_idx, 5, f"{fe}×", hs_bg, "111111", True)
        val(ws8, r_idx, 6, ", ".join(str(p) for p in hs.get("positions", [])[:30]), sz=9)

    # Sheet 9: Literature / Papers
    ws9 = wb.create_sheet("📚 Literature")
    ws9.sheet_view.showGridLines = False
    for col, (name, w) in enumerate([("PMID", 12), ("Title", 80), ("Authors", 35), ("Journal", 30), ("Year", 8), ("PubMed URL", 40)], 1):
        ws9.column_dimensions[get_column_letter(col)].width = w
        hdr(ws9, 1, col, name, DARK, CYAN)

    all_papers = papers + [p2 for p2 in (st.session_state.get("abstracts", []) or []) if p2.get("pmid", "") not in {p3.get("pmid", "") for p3 in papers}]
    for r_idx, p_e in enumerate(all_papers, 2):
        val(ws9, r_idx, 1, p_e.get("pmid", ""), None, "0066AA", True)
        val(ws9, r_idx, 2, p_e.get("title", "")[:150])
        val(ws9, r_idx, 3, p_e.get("authors", "")[:60])
        val(ws9, r_idx, 4, p_e.get("journal", "")[:35])
        val(ws9, r_idx, 5, p_e.get("year", ""))
        url_p = p_e.get("url", "")
        cell_p = val(ws9, r_idx, 6, url_p, None, "0066AA")
        if url_p:
            cell_p.hyperlink = url_p
            cell_p.style = "Hyperlink"

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
